---
# 清空 ZMK_EXTRA_MODULES，避免「BOARD_ROOT element without a 'boards' subdirectory」警告
# （本仓库为纯 config，板级由 west 的 eyelash_corne / nice-view-gem 提供）
include:
#  - board: eyelash_corne_left
#    shield: nice_view
#    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_view_gem
    cmake-args: -DZMK_EXTRA_MODULES=
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DZMK_EXTRA_MODULES=
    artifact-name: eyelash_corne_studio_left
  - board: nice_nano_v2
    shield: settings_reset
    cmake-args: -DZMK_EXTRA_MODULES=
    #snippet: zmk-usb-logging
 
